#!/usr/bin/env bash

if ! echo $PATH | grep ~/.cargo/bin > /dev/null; then
  export PATH="~/.cargo/bin:$PATH"
fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
if ! echo $PATH | grep ~/.rvm/bin > /dev/null; then
  export PATH="$PATH:~/.rvm/bin"
fi

unset FZF_DEFAULT_OPTS
export FZF_DEFAULT_OPTS='--bind alt-j:preview-page-down --bind alt-k:preview-page-up --bind ctrl-l:select-all --bind ctrl-n:deselect-all'
export FZF_CTRL_T_OPTS='--bind "enter:execute(echo -n {+} | xargs copy-path-to-clipboard)+accept"'

# Show history with fzf e copy the selection to clipboard
bind -x '"\C-x\C-r": "history | tac | fzf -m | xsel -b"'

# Binds for git refs
bind '"\C-g\C-b": " \C-u \C-a\C-k`git fshow branch`\e\C-e\C-y\C-a\C-y\ey\C-h\C-e\er \C-h"'
bind '"\C-g\C-r": " \C-u \C-a\C-k`git fshow branch -r`\e\C-e\C-y\C-a\C-y\ey\C-h\C-e\er \C-h"'
bind '"\C-g\C-t": " \C-u \C-a\C-k`git fshow tag --sort -version:refname`\e\C-e\C-y\C-a\C-y\ey\C-h\C-e\er \C-h"'
bind '"\C-g\C-h": " \C-u \C-a\C-k`git fshow lgg --all`\e\C-e\C-y\C-a\C-y\ey\C-h\C-e\er \C-h"'
