#!/usr/bin/env bash

cmake .. \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DCMAKE_BUILD_TYPE=None \
    -DCOMPIZ_BUILD_WITH_RPATH=FALSE \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCOMPIZ_PACKAGING_ENABLED=TRUE \
    -DUSE_GSETTINGS=ON \
    -DCOMPIZ_DISABLE_GS_SCHEMAS_INSTALL=OFF \
    -DCOMPIZ_DISABLE_PLUGIN_KDE=ON \
    -DCOMPIZ_BUILD_TESTING=OFF \
    -DUSE_KDE4=OFF \
    -DUSE_GCONF=OFF
